version: '3'
services:
  mongodb:
    image: mongo
    container_name: container-mongo__milky_task_service
    environment:
      MONGO_INITDB_ROOT_USERNAME: milky_task_db_user
      MONGO_INITDB_ROOT_PASSWORD: milky_task_db_password
      MONGO_INITDB_DATABASE: milky_task_db
      AUTH: "SCRAM-SHA-1"
    command: ["--auth"]
    ports:
      - "27017:27017"
